name: old_school_demos
description: Demos for the Dart library, Old School.
version: 0.3.0
homepage: https://github.com/ram6ler/old_school_demos

environment:
  sdk: ">=3.6.0 <4.0.0"
dependencies:
  old_school: ^0.4.0
  poker_simulations: ^0.1.2
  web: ^1.1.1
dev_dependencies:
  lints: ^6.0.0
  
